<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <UseWPF>true</UseWPF>
        <OutputType>WinExe</OutputType>
        <UseWindowsForms>true</UseWindowsForms>
        <RootNamespace>$(AssemblyName)</RootNamespace>
        <AssemblyName>Sucrose.Live.Aurora</AssemblyName>
        <StartupObject>$(AssemblyName).App</StartupObject>
        <DefineConstants>$(DefineConstants);ENGINE;LIVE_AURORA</DefineConstants>
        <OutputPath Condition="'$(PlatformTarget)' == 'x86'">..\..\Sucrose\Live\Aurora\x86</OutputPath>
        <OutputPath Condition="'$(PlatformTarget)' == 'x64'">..\..\Sucrose\Live\Aurora\x64</OutputPath>
        <OutputPath Condition="'$(PlatformTarget)' == 'arm64'">..\..\Sucrose\Live\Aurora\ARM64</OutputPath>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <AppHostDotNetSearch>AppRelative</AppHostDotNetSearch>
        <AppHostDotnetRoot>..\Sucrose.Runtime</AppHostDotnetRoot>
        <AppHostRelativeDotNet>..\Sucrose.Runtime</AppHostRelativeDotNet>
        <InterceptorsNamespaces>$(InterceptorsNamespaces);Microsoft.Extensions.Configuration.Binder.SourceGeneration</InterceptorsNamespaces>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Skylark.Wing" />
        <PackageReference Include="RawInput.Sharp" />
        <PackageReference Include="Skylark.Standard" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Library\Sucrose.Manager\Sucrose.Manager.csproj" />
        <ProjectReference Include="..\..\Library\Sucrose.Resources\Sucrose.Resources.csproj" />
    </ItemGroup>

    <Import Project="..\..\Shared\Sucrose.Shared.Zip\Sucrose.Shared.Zip.projitems" Label="Shared" />
    <Import Project="..\..\Shared\Sucrose.Shared.Live\Sucrose.Shared.Live.projitems" Label="Shared" />
    <Import Project="..\..\Shared\Sucrose.Shared.Space\Sucrose.Shared.Space.projitems" Label="Shared" />
    <Import Project="..\..\Shared\Sucrose.Shared.Theme\Sucrose.Shared.Theme.projitems" Label="Shared" />
    <Import Project="..\..\Shared\Sucrose.Shared.Watchdog\Sucrose.Shared.Watchdog.projitems" Label="Shared" />
    <Import Project="..\..\Shared\Engine\Sucrose.Shared.Engine\Sucrose.Shared.Engine.projitems" Label="Shared" />
    <Import Project="..\..\Shared\Sucrose.Shared.Dependency\Sucrose.Shared.Dependency.projitems" Label="Shared" />
    <Import Project="..\..\Shared\Engine\Sucrose.Shared.Engine.Aurora\Sucrose.Shared.Engine.Aurora.projitems" Label="Shared" />

    <PropertyGroup>
        <SourceDirectory>$(OutputPath)\$(TargetFramework)\win-$(Platform)</SourceDirectory>
        <DestinationDirectory>..\..\Sucrose\Package\$(TargetFramework)\$(Platform)\$(AssemblyName)\</DestinationDirectory>
    </PropertyGroup>

</Project>