<Project>
    <PropertyGroup>
        <Authors>Taiizor</Authors>
        <Company>Taiizor</Company>
        <Optimize>false</Optimize>
        <Product>$(Title)</Product>
        <Nullable>disable</Nullable>
        <LangVersion>preview</LangVersion>
        <Description>$(Title)</Description>
        <Platforms>ARM64;x64;x86</Platforms>
        <FileVersion>$(Version)</FileVersion>
        <AnalysisLevel>preview</AnalysisLevel>
        <ImplicitUsings>enable</ImplicitUsings>
        <Title>Sucrose Wallpaper Engine</Title>
        <AssemblyVersion>$(Version)</AssemblyVersion>
        <TargetFrameworks>net9.0-windows</TargetFrameworks>
        <NoWarn>$(NoWarn);CS8632;WFO0003,SYSLIB0014</NoWarn>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <InformationalVersion>$(Version)</InformationalVersion>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
        <RuntimeIdentifiers>win-arm64;win-x64;win-x86</RuntimeIdentifiers>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <AppendTargetFrameworkToOutputPath>true</AppendTargetFrameworkToOutputPath>
        <Copyright>Copyright © $([System.DateTime]::Today.ToString(yyyy)) $(Company)</Copyright>
        <Version>$([System.DateTime]::Today.ToString(yy)).$([System.DateTime]::Today.ToString(MM)).$([System.DateTime]::Today.ToString(dd))</Version>
    </PropertyGroup>

    <PropertyGroup>
        <BaseOutputPath>..\..\Sucrose</BaseOutputPath>
        <BaseIntermediateOutputPath>$(BaseOutputPath)\Object\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
    </PropertyGroup>

    <PropertyGroup>
        <NuGetAudit>true</NuGetAudit>
        <NuGetAuditLevel>moderate</NuGetAuditLevel>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
        <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>
        <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    </PropertyGroup>

    <PropertyGroup>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Properties\" />
    </ItemGroup>
</Project>