<Project>
    <PropertyGroup Condition="'$(OutputType)' != 'Library'">
        <ApplicationIcon>Assets\ICO.ico</ApplicationIcon>
        <ApplicationManifest>App.manifest</ApplicationManifest>
    </PropertyGroup>

    <PropertyGroup Condition="'$(OutputType)' != 'Library'">
        <ThreadPoolMinThreads>10</ThreadPoolMinThreads>
        <ThreadPoolMaxThreads>250</ThreadPoolMaxThreads>
        <UseWindowsThreadPool>true</UseWindowsThreadPool>
        <ServerGarbageCollection>true</ServerGarbageCollection>
        <RetainVMGarbageCollection>false</RetainVMGarbageCollection>
        <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
        <!-- Supported as of .NET Core SDK 3.0 Preview 1 -->
        <TieredCompilation>true</TieredCompilation>
        <InvariantGlobalization>false</InvariantGlobalization>
    </PropertyGroup>

    <PropertyGroup Condition="'$(PlatformTarget)' == 'x86'">
        <DefineConstants>$(DefineConstants);X86</DefineConstants>
        <SelfContained Condition="'$(SelfContained)' == ''">false</SelfContained>
        <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == ''">win-x86</RuntimeIdentifier>
    </PropertyGroup>

    <PropertyGroup Condition="'$(PlatformTarget)' == 'x64'">
        <DefineConstants>$(DefineConstants);X64</DefineConstants>
        <SelfContained Condition="'$(SelfContained)' == ''">false</SelfContained>
        <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == ''">win-x64</RuntimeIdentifier>
    </PropertyGroup>

    <PropertyGroup Condition="'$(PlatformTarget)' == 'arm64'">
        <DefineConstants>$(DefineConstants);ARM64</DefineConstants>
        <SelfContained Condition="'$(SelfContained)' == ''">false</SelfContained>
        <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == ''">win-arm64</RuntimeIdentifier>
    </PropertyGroup>

    <ItemGroup Condition="'$(OutputType)' != 'Library'">
        <AppConfigWithTargetPath Include="App.$(TargetFramework).config">
            <TargetPath>$(AssemblyName).exe.config</TargetPath>
        </AppConfigWithTargetPath>
    </ItemGroup>

    <Target Name="CopyFiles" BeforeTargets="Build" Condition="'$(OutputType)' != 'Library' AND '$(Configuration)' == 'Debug'">
        <ItemGroup>
            <FilesToCopy Include="$(SourceDirectory)\**\*.*" />
        </ItemGroup>
        <Copy SourceFiles="@(FilesToCopy)" DestinationFiles="@(FilesToCopy->'$(DestinationDirectory)%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
    </Target>
</Project>