<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <StartupObject>$(AssemblyName).App</StartupObject>
        <AssemblyName>Sucrose.Backgroundog</AssemblyName>
        <RootNamespace>$(AssemblyName)</RootNamespace>
        <UseWindowsForms>true</UseWindowsForms>
        <UseWPF>true</UseWPF>
        <DefineConstants>$(DefineConstants);BACKGROUNDOG</DefineConstants>
        <OutputPath Condition="'$(PlatformTarget)' == 'x86'">..\..\Sucrose\Backgroundog\x86</OutputPath>
        <OutputPath Condition="'$(PlatformTarget)' == 'x64'">..\..\Sucrose\Backgroundog\x64</OutputPath>
        <OutputPath Condition="'$(PlatformTarget)' == 'arm64'">..\..\Sucrose\Backgroundog\ARM64</OutputPath>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <AppHostDotNetSearch>AppRelative</AppHostDotNetSearch>
        <AppHostDotnetRoot>..\Sucrose.Runtime</AppHostDotnetRoot>
        <AppHostRelativeDotNet>..\Sucrose.Runtime</AppHostRelativeDotNet>
        <InterceptorsNamespaces>$(InterceptorsNamespaces);Microsoft.Extensions.Configuration.Binder.SourceGeneration</InterceptorsNamespaces>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="NAudio" Version="2.2.1" />
        <PackageReference Include="NPSMLib" Version="0.9.14" />
        <PackageReference Include="Skylark.Wing" Version="3.1.8.6" />
        <PackageReference Include="Skylark.Standard" Version="3.1.7.2" />
        <PackageReference Include="MathNet.Numerics" Version="6.0.0-beta2" />
        <PackageReference Include="LibreHardwareMonitorLib" Version="0.9.5-pre497" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Library\Sucrose.Pipe\Sucrose.Pipe.csproj" />
        <ProjectReference Include="..\..\Library\Sucrose.Signal\Sucrose.Signal.csproj" />
        <ProjectReference Include="..\..\Library\Sucrose.Manager\Sucrose.Manager.csproj" />
        <ProjectReference Include="..\..\Library\Sucrose.Transmission\Sucrose.Transmission.csproj" />
    </ItemGroup>

    <Import Project="..\..\Shared\Sucrose.Shared.Live\Sucrose.Shared.Live.projitems" Label="Shared" />
    <Import Project="..\..\Shared\Sucrose.Shared.Space\Sucrose.Shared.Space.projitems" Label="Shared" />
    <Import Project="..\..\Shared\Sucrose.Shared.Theme\Sucrose.Shared.Theme.projitems" Label="Shared" />
    <Import Project="..\..\Shared\Sucrose.Shared.Watchdog\Sucrose.Shared.Watchdog.projitems" Label="Shared" />
    <Import Project="..\..\Shared\Sucrose.Shared.Dependency\Sucrose.Shared.Dependency.projitems" Label="Shared" />

    <PropertyGroup>
        <SourceDirectory>$(OutputPath)\$(TargetFramework)\win-$(Platform)</SourceDirectory>
        <DestinationDirectory>..\..\Sucrose\Package\$(TargetFramework)\$(Platform)\$(AssemblyName)\</DestinationDirectory>
    </PropertyGroup>

</Project>