<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <UseWPF>false</UseWPF>
        <OutputType>Exe</OutputType>
        <UseWindowsForms>false</UseWindowsForms>
        <AssemblyName>Sucrose.Localizer</AssemblyName>
        <RootNamespace>$(AssemblyName)</RootNamespace>
        <StartupObject>$(AssemblyName).App</StartupObject>
        <DefineConstants>$(DefineConstants);LOCALIZER</DefineConstants>
        <OutputPath Condition="'$(PlatformTarget)' == 'x86'">..\..\Sucrose\Localizer\x86</OutputPath>
        <OutputPath Condition="'$(PlatformTarget)' == 'x64'">..\..\Sucrose\Localizer\x64</OutputPath>
        <OutputPath Condition="'$(PlatformTarget)' == 'arm64'">..\..\Sucrose\Localizer\ARM64</OutputPath>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <AppHostDotNetSearch>AppRelative</AppHostDotNetSearch>
        <AppHostDotnetRoot>..\Sucrose.Runtime</AppHostDotnetRoot>
        <AppHostRelativeDotNet>..\Sucrose.Runtime</AppHostRelativeDotNet>
        <InterceptorsNamespaces>$(InterceptorsNamespaces);Microsoft.Extensions.Configuration.Binder.SourceGeneration</InterceptorsNamespaces>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CsvHelper" />
        <PackageReference Include="Skylark.Standard" />
    </ItemGroup>

</Project>