<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <StartupObject>$(AssemblyName).App</StartupObject>
        <AssemblyName>Sucrose.Undo</AssemblyName>
        <RootNamespace>$(AssemblyName)</RootNamespace>
        <UseWindowsForms>false</UseWindowsForms>
        <UseWPF>true</UseWPF>
        <DefineConstants>$(DefineConstants);UNDO</DefineConstants>
        <OutputPath Condition="'$(PlatformTarget)' == 'x86'">..\..\Sucrose\Undo\x86</OutputPath>
        <OutputPath Condition="'$(PlatformTarget)' == 'x64'">..\..\Sucrose\Undo\x64</OutputPath>
        <OutputPath Condition="'$(PlatformTarget)' == 'arm64'">..\..\Sucrose\Undo\ARM64</OutputPath>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <AppHostDotNetSearch>AppRelative</AppHostDotNetSearch>
        <AppHostDotnetRoot>..\Sucrose.Runtime</AppHostDotnetRoot>
        <AppHostRelativeDotNet>..\Sucrose.Runtime</AppHostRelativeDotNet>
        <InterceptorsNamespaces>$(InterceptorsNamespaces);Microsoft.Extensions.Configuration.Binder.SourceGeneration</InterceptorsNamespaces>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Skylark.Wing" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Library\Sucrose.Resources\Sucrose.Resources.csproj" />
    </ItemGroup>

    <PropertyGroup>
        <SourceDirectory>$(OutputPath)\$(TargetFramework)\win-$(Platform)</SourceDirectory>
        <DestinationDirectory>..\..\Sucrose\Package\$(TargetFramework)\$(Platform)\$(AssemblyName)\</DestinationDirectory>
    </PropertyGroup>

</Project>
