<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFrameworks>net48</TargetFrameworks>
        <StartupObject>$(RootNamespace).App</StartupObject>
        <AssemblyName>Sucrose.Bundle</AssemblyName>
        <RootNamespace>$(RootNamespace)</RootNamespace>
        <UseWindowsForms>false</UseWindowsForms>
        <UseWPF>true</UseWPF>
        <OutputPath Condition="'$(PlatformTarget)' == 'x86'">..\..\Sucrose\Bundle\x86</OutputPath>
        <OutputPath Condition="'$(PlatformTarget)' == 'x64'">..\..\Sucrose\Bundle\x64</OutputPath>
        <OutputPath Condition="'$(PlatformTarget)' == 'arm64'">..\..\Sucrose\Bundle\ARM64</OutputPath>
    </PropertyGroup>

    <PropertyGroup>
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="SharpCompress" Version="0.40.0" />
        <PackageReference Include="Skylark.Wing" Version="3.1.8.6" />
        <PackageReference Include="Skylark.Standard" Version="3.1.7.2" />
        <PackageReference Include="Costura.Fody" Version="6.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>compile; runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <Resource Include="Assets\**" />
    </ItemGroup>
    
    <ItemGroup>
        <EmbeddedResource Include="SevenZip\7z-$(Platform)\**">
            <LogicalName>SevenZip\%(RecursiveDir)%(FileName)%(Extension)</LogicalName>
        </EmbeddedResource>
        <EmbeddedResource Include="Showcase\**">
            <LogicalName>Showcase\%(RecursiveDir)%(FileName)%(Extension)</LogicalName>
        </EmbeddedResource>
        <EmbeddedResource Include="..\..\Sucrose\Package\Cache\net9.0-windows\$(Platform)\**">
            <LogicalName>Caches\%(RecursiveDir)%(FileName)%(Extension)</LogicalName>
        </EmbeddedResource>
        <EmbeddedResource Include="..\..\Sucrose\Package\Compressed\net9.0-windows\Sucrose-$(Platform).7z">
            <LogicalName>Packages\%(RecursiveDir)Sucrose%(Extension)</LogicalName>
        </EmbeddedResource>
    </ItemGroup>

    <PropertyGroup>
        <SourceDirectory>$(OutputPath)\$(TargetFramework)\win-$(Platform)</SourceDirectory>
        <DestinationDirectory>..\..\Sucrose\Package\$(TargetFramework)\$(Platform)\$(AssemblyName)\</DestinationDirectory>
    </PropertyGroup>

</Project>