<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <UseWPF>true</UseWPF>
        <OutputType>WinExe</OutputType>
        <UseWindowsForms>false</UseWindowsForms>
        <TargetFrameworks>net48</TargetFrameworks>
        <AssemblyName>Sucrose.Bundle</AssemblyName>
        <RootNamespace>$(RootNamespace)</RootNamespace>
        <StartupObject>$(RootNamespace).App</StartupObject>
        <OutputPath Condition="'$(PlatformTarget)' == 'x86'">$(BaseOutputPath)\Bundle\x86</OutputPath>
        <OutputPath Condition="'$(PlatformTarget)' == 'x64'">$(BaseOutputPath)\Bundle\x64</OutputPath>
        <OutputPath Condition="'$(PlatformTarget)' == 'arm64'">$(BaseOutputPath)\Bundle\ARM64</OutputPath>
    </PropertyGroup>

    <PropertyGroup>
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Skylark.Wing" />
        <PackageReference Include="SharpCompress" />
        <PackageReference Include="Skylark.Standard" />
        <PackageReference Include="Costura.Fody">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>compile; runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <Resource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Showcase\**">
            <LogicalName>Showcase\%(RecursiveDir)%(FileName)%(Extension)</LogicalName>
        </EmbeddedResource>
        <EmbeddedResource Include="Checksum\*.html">
            <LogicalName>Checksum\%(RecursiveDir)%(FileName)%(Extension)</LogicalName>
        </EmbeddedResource>
        <EmbeddedResource Include="Checksum\$(Platform)\**">
            <LogicalName>Checksum\%(RecursiveDir)%(FileName)%(Extension)</LogicalName>
        </EmbeddedResource>
        <EmbeddedResource Include="SevenZip\7z-$(Platform)\**">
            <LogicalName>SevenZip\%(RecursiveDir)%(FileName)%(Extension)</LogicalName>
        </EmbeddedResource>
        <EmbeddedResource Include="$(BaseOutputPath)\Package\Compressed\net9.0-windows\Sucrose-$(Platform).7z">
            <LogicalName>Packages\%(RecursiveDir)Sucrose%(Extension)</LogicalName>
        </EmbeddedResource>
    </ItemGroup>

</Project>