<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <UseWPF>true</UseWPF>
        <OutputType>WinExe</OutputType>
        <UseWindowsForms>false</UseWindowsForms>
        <AssemblyName>Sucrose.Watchdog</AssemblyName>
        <RootNamespace>$(AssemblyName)</RootNamespace>
        <StartupObject>$(AssemblyName).App</StartupObject>
        <DefineConstants>$(DefineConstants);WATCHDOG</DefineConstants>
        <OutputPath Condition="'$(PlatformTarget)' == 'x86'">..\..\Sucrose\Watchdog\x86</OutputPath>
        <OutputPath Condition="'$(PlatformTarget)' == 'x64'">..\..\Sucrose\Watchdog\x64</OutputPath>
        <OutputPath Condition="'$(PlatformTarget)' == 'arm64'">..\..\Sucrose\Watchdog\ARM64</OutputPath>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <AppHostDotNetSearch>AppRelative</AppHostDotNetSearch>
        <AppHostDotnetRoot>..\Sucrose.Runtime</AppHostDotnetRoot>
        <AppHostRelativeDotNet>..\Sucrose.Runtime</AppHostRelativeDotNet>
        <InterceptorsNamespaces>$(InterceptorsNamespaces);Microsoft.Extensions.Configuration.Binder.SourceGeneration</InterceptorsNamespaces>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Skylark.Wing" />
        <PackageReference Include="Skylark.Standard" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Library\Sucrose.Manager\Sucrose.Manager.csproj" />
        <ProjectReference Include="..\..\Library\Sucrose.Resources\Sucrose.Resources.csproj" />
    </ItemGroup>

    <Import Project="..\..\Shared\Sucrose.Shared.Core\Sucrose.Shared.Core.projitems" Label="Shared" />
    <Import Project="..\..\Shared\Sucrose.Shared.Live\Sucrose.Shared.Live.projitems" Label="Shared" />
    <Import Project="..\..\Shared\Sucrose.Shared.Space\Sucrose.Shared.Space.projitems" Label="Shared" />
    <Import Project="..\..\Shared\Sucrose.Shared.Theme\Sucrose.Shared.Theme.projitems" Label="Shared" />
    <Import Project="..\..\Shared\Sucrose.Shared.Watchdog\Sucrose.Shared.Watchdog.projitems" Label="Shared" />
    <Import Project="..\..\Shared\Sucrose.Shared.Dependency\Sucrose.Shared.Dependency.projitems" Label="Shared" />

    <ItemGroup>
        <Resource Include="Assets\**\*.*" />
    </ItemGroup>

    <PropertyGroup>
        <SourceDirectory>$(OutputPath)\$(TargetFramework)\win-$(Platform)</SourceDirectory>
        <DestinationDirectory>..\..\Sucrose\Package\$(TargetFramework)\$(Platform)\$(AssemblyName)\</DestinationDirectory>
    </PropertyGroup>

</Project>